name: "Train-in-the-cloud"
on: [workflow_dispatch]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: "Deploy runner on EC2"
        shell: bash
        env:
          repo_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-east-1 \
          --cloud-type=p3.2xlarge \
          --cloud-gpu=v100 \
          --single=true \
          --labels=cml-runner
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: "Train my model"
      env:
        repo_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        # Install requirements
        pip install -r requirements.txt
        
        # Provide local secret for Azure Connection String
        dvc remote modify --local azuredata connection_string ''

        # Pull data & run-cache from S3 and reproduce pipeline
        dvc pull data --run-cache

        # Train the model
        dvc repro

        # Publish report with CML
        cat metrics.txt > report.md
        cml-send-comment report.md
