name: "Train-in-the-cloud"
on: [pull_request]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: "Deploy runner on EC2"
        shell: bash
        env:
          repo_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-east-1 \
          --cloud-type=t2.micro \
          --single=true \
          --labels=cml-runner
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: "Train my model"
      env:
        repo_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        # Install requirements
        pip install -r requirements.txt
        
        # Provide local secret for Azure Connection String
        dvc remote modify --local azuredata connection_string ''

        # Pull with get_data & run-cache from S3 and reproduce pipeline
        dvc pull get_data --run-cache

        # Train the model
        dvc repro
        
        # Push new data to the repository, may require permissions, so commenting for now.
        #dvc push

        git fetch --prune

        # Add differential of branch metrics from main to the report
        dvc metrics diff --show-md main > report.md

        echo "## Validating results by region"
        
        # Add figure to the report
        cml-publish by_region.png --md >> report.md
        
        # Publish report with CML
        cml-send-comment report.md
